FROM rockylinux:9
MAINTAINER Sumo Logic <collection@sumologic.com>

RUN dnf install -y \
    which \
    make \
    rpm-build \
    selinux-policy \
    selinux-policy-devel \
    git \
    systemd

RUN curl -Lo cmake.sh https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-linux-aarch64.sh
RUN chmod +x cmake.sh
RUN ./cmake.sh --skip-license --prefix=/usr
RUN rm cmake.sh

WORKDIR /src/build
