include("${UTILS_DIR}/variables.cmake")
include("${UTILS_DIR}/cpack-state.cmake")
include("${UTILS_DIR}/property.cmake")
include("${UTILS_DIR}/build-validation.cmake")
include("${UTILS_DIR}/targets.cmake")
include("${UTILS_DIR}/detect_version.cmake")
