name: 'Run make'

inputs:
  target:
    required: true
    type: string
  gh_token:
    required: false
    type: string
  packagecloud_token:
    required: false
    type: string
  aws-access-key-id:
    required: false
    type: string
  aws-secret-access-key:
    required: false
    type: string
  s3_bucket:
    required: true
    type: string

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    GH_TOKEN: ${{ inputs.gh_token }}
    PACKAGECLOUD_TOKEN: ${{ inputs.packagecloud_token }}
    s3_bucket: ${{ inputs.s3_bucket}}
  args:
    - make
    - ${{ inputs.target }}
