name: 'Run make'

inputs:
  target:
    required: true
    type: string
  gh_token:
    required: false
    type: string
  packagecloud_token:
    required: false
    type: string

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    GH_TOKEN: ${{ inputs.gh_token }}
    PACKAGECLOUD_TOKEN: ${{ inputs.packagecloud_token }}
  args:
    - make
    - ${{ inputs.target }}
