# Takes a list of variable names and ensures each variable is defined
function(require_variables varNames)
  foreach(varName ${varNames})
    if(NOT DEFINED ${varName})
      message(FATAL_ERROR "required variable is not set: ${varName}")
    endif()
  endforeach()
endfunction()

# Print out all variables (for debugging)
function(print_all_variables)
  get_cmake_property(_variableNames VARIABLES)
  list (SORT _variableNames)
  foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
  endforeach()
endfunction()
