#!/usr/bin/env bash
# Usage: ./s3_cp_no_checks.sh ACCESS_KEY_ENV_VAR SECRET_KEY_ENV_VAR S3_BUCKET S3_PATH FILE_PATH

ACCESS_VAR_NAME="$1"
SECRET_VAR_NAME="$2"
S3_BUCKET="$3"
S3_PATH="$4"
FILE_PATH="$5"

ACCESS_KEY="${!ACCESS_VAR_NAME}"
SECRET_KEY="${!SECRET_VAR_NAME}"

S3_URI="s3://${S3_BUCKET%/}/${S3_PATH#/}"

AWS_ACCESS_KEY_ID="$ACCESS_KEY" AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
  aws s3 cp "$FILE_PATH" "$S3_URI"

echo "Upload attempted to $S3_URI"