name: 'Run CMake'

inputs:
  otc_version:
    required: true
    type: string
  otc_sumo_version:
    required: true
    type: string
  otc_build_number:
    required: false
    type: string
  target:
    required: true
    type: string
  workflow_id:
    required: false
    type: string

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    TARGET: ${{ inputs.target }}
  args:
    - cmake
    - ../
