name: 'Run CMake'

inputs:
  args:
    required: false
    type: string
    default: '../'
  otc_build_number:
    required: false
    type: string
  target:
    required: true
    type: string
  work_dir:
    required: false
    type: string
  workflow_id:
    required: false
    type: string
  gh_token:
    required: false
    type: string

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    GH_TOKEN: ${{ inputs.gh_token }}
    GH_WORKFLOW_ID: ${{ inputs.workflow_id }}
    OTC_BUILD_NUMBER: ${{ inputs.otc_build_number }}
    TARGET: ${{ inputs.target }}
    WORK_DIR: ${{ inputs.work_dir }}
  args:
    - cmake
    - ${{ inputs.args }}
