name: 'Dev builds'

on: [push]

jobs:
  build_package:
    name: ${{ matrix.target }}
    uses: ./.github/workflows/build_package.yml
    with:
      otc_version: "0.69.0"
      otc_sumo_version: "0"
      otc_build_number: ${{ github.run_number }}
      make_target: ${{ matrix.target }}
    strategy:
      matrix:
        target:
          - package-otelcol-sumo-linux-amd64-deb
          - package-otelcol-sumo-linux-amd64-rpm
