name: 'Lint'

permissions: {}

on:
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_VERSION: 0.9.0
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck on *.sh
        uses: ludeeus/action-shellcheck@master

      - name: Run ShellCheck on hook templates
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: 'templates/hooks'
          additional_files: '*.in'
