name: 'Lint'

permissions: {}

on:
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck on *.sh
        uses: ludeeus/action-shellcheck@master
        with:
          severity: info  # TODO: check if we can resolve the style issues as well

      - name: Run ShellCheck on hook templates
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: 'templates/hooks'
          additional_files: '*.in'
