name: 'Lint'

permissions: {}

on:
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck on *.sh
        uses: ludeeus/action-shellcheck@master
        with:
          # TODO: remove this after fixing shellcheck warnings for install.sh
          ignore_paths: ./install-script/install.sh

      - name: Run ShellCheck on hook templates
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: 'templates/hooks'
          additional_files: '*.in'
