name: File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Sync Files
        uses: BetaHuhn/repo-file-sync-action@v1.21.0
        with:
          GH_PAT: ${{ secrets.FILE_SYNC_GH_TOKEN }}
