name: 'Test install script'

defaults:
  run:
    shell: bash

on:
  pull_request:

jobs:
  test-install-script:
    name: Test Install Script
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_os: linux_amd64
            runs_on: ubuntu-20.04
          - arch_os: darwin_amd64
            runs_on: macos-latest
          - arch_os: windows_amd64
            runs_on: windows-2022
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check if test related files changed
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            install-script/**/*
            .github/**

      - name: Setup go
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: stable

      - name: Run install script tests
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: install-script/test
        run: make test
